name: approve_and_label
on: 
  pull_request:
    types: [opened, reopened]
    
env:
  # Customise this variable to choose which dependencies can be auto-merged
  AUTO_MERGE_PACKAGE_FILTER: |
    ["Endjin.*","Corvus.*"]

jobs:
  evaluate_dependabot_pr:
    runs-on: ubuntu-latest
    name: Parse Dependabot PR title
    outputs:
      dependency_name: ${{ steps.parse_dependabot_pr.outputs.dependency_name }}
      is_auto_merge_candidate: ${{ steps.parse_dependabot_pr.outputs.is_interesting_package }}
      update_type: ${{ steps.parse_dependabot_pr.outputs.update_type }}
    if: |
      (github.actor == 'dependabot[bot]' || github.actor == 'nektos/act') &&
      github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
      - name: Parse Dependabot PR title
        id: parse_dependabot_pr
        uses: endjin/dependabot-pr-parser@v2
        with:
          pr_title: ${{ github.event.pull_request.title }}
          package_filter: ${{ env.AUTO_MERGE_PACKAGE_FILTER }}
      - name: debug
        run: |
          echo "dependency_name : ${{ steps.parse_dependabot_pr.outputs.dependency_name }}"
          echo "is_interesting_package : ${{ steps.parse_dependabot_pr.outputs.is_interesting_package }}"
          echo "update_type : ${{ steps.parse_dependabot_pr.outputs.update_type }}"
  approve_and_label:
    runs-on: ubuntu-latest
    needs: evaluate_dependabot_pr
    name: Approve and label
    if: |
      (github.actor == 'dependabot[bot]' || github.actor == 'nektos/act') &&
      github.event_name == 'pull_request'
    steps:
      - name: debug
        run: |
          env
          cat "$GITHUB_EVENT_PATH"
          echo "<------------------------------------------------>"
          echo "dependency_name : ${{needs.evaluate_dependabot_pr.outputs.dependency_name}}"
          echo "update_type     : ${{needs.evaluate_dependabot_pr.outputs.update_type}}"
          echo "auto_merge      : ${{needs.evaluate_dependabot_pr.outputs.is_auto_merge_candidate}}"
          echo "<------------------------------------------------>"
        shell: bash
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          ENDJIN_BOT_APP_ID: ${{ secrets.ENDJIN_BOT_APP_ID }}
          ENDJIN_BOT_PRIVATE_KEY: ${{ secrets.ENDJIN_BOT_PRIVATE_KEY }}
      - name: Approve pull request
        if: |
          needs.evaluate_dependabot_pr.outputs.is_auto_merge_candidate == 'True' &&
          (needs.evaluate_dependabot_pr.outputs.update_type == 'minor' || needs.evaluate_dependabot_pr.outputs.update_type == 'patch')
        uses: andrewmusgrave/automatic-pull-request-review@0.0.2
        with:
          repo-token: '${{ steps.generate_token.outputs.token }}'
          event: APPROVE
          body: 'Thank you dependabot 🎊'
      - name: 'Label with "autosquash"'
        if: |
          needs.evaluate_dependabot_pr.outputs.is_auto_merge_candidate == 'True' &&
          (needs.evaluate_dependabot_pr.outputs.update_type == 'minor' || needs.evaluate_dependabot_pr.outputs.update_type == 'patch')
        env: 
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
        uses: actions/github-script@v2
        with:
          github-token: '${{ steps.generate_token.outputs.token }}'
          script: |
            await github.issues.addLabels({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              issue_number: context.payload.pull_request.number,
              labels: ['autosquash']
            })
