//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Runtime.CompilerServices;
using System.Text.Json;
using System.Text.RegularExpressions;
using Corvus.Json;
using Corvus.Json.Internal;

namespace Menes.OpenApiSchema.V31;
public readonly partial struct Document
{
    /// <summary>
    /// A type generated from a JsonSchema specification.
    /// </summary>
    public readonly partial struct Components
    {
        /// <summary>
        /// A pattern property matching ^(schemas|responses|parameters|examples|requestBodies|headers|securitySchemes|links|callbacks|pathItems)$ producing a <see cref = "Menes.OpenApiSchema.V31.Document.Components.SchemasResponsesParametersExamplesRequestBodiesHeadersSecuritySchemesLinksCallbacksPathItemsEntity"/>.
        /// </summary>
        public static Regex PatternPropertySchemasResponsesParametersExamplesRequestBodiesHeadersSecuritySchemesLinksCallbacksPathItemsEntity => new("^(schemas|responses|parameters|examples|requestBodies|headers|securitySchemes|links|callbacks|pathItems)$", RegexOptions.Compiled, TimeSpan.FromSeconds(1));
        private static readonly ImmutableDictionary<Regex, PatternPropertyValidator> __CorvusPatternProperties = CreatePatternPropertiesValidators();
        /// <summary>
        /// Determines if a property matches ^(schemas|responses|parameters|examples|requestBodies|headers|securitySchemes|links|callbacks|pathItems)$ producing a <see cref = "Menes.OpenApiSchema.V31.Document.Components.SchemasResponsesParametersExamplesRequestBodiesHeadersSecuritySchemesLinksCallbacksPathItemsEntity"/>.
        /// </summary>
        public bool MatchesPatternSchemasResponsesParametersExamplesRequestBodiesHeadersSecuritySchemesLinksCallbacksPathItemsEntity(in JsonObjectProperty property)
        {
            return PatternPropertySchemasResponsesParametersExamplesRequestBodiesHeadersSecuritySchemesLinksCallbacksPathItemsEntity.IsMatch(property.Name);
        }

        /// <summary>
        /// Get a property value as the type matching the given pattern property ^(schemas|responses|parameters|examples|requestBodies|headers|securitySchemes|links|callbacks|pathItems)$ as a <see cref = "Menes.OpenApiSchema.V31.Document.Components.SchemasResponsesParametersExamplesRequestBodiesHeadersSecuritySchemesLinksCallbacksPathItemsEntity"/>.
        /// </summary>
        public bool TryAsPatternSchemasResponsesParametersExamplesRequestBodiesHeadersSecuritySchemesLinksCallbacksPathItemsEntity(in JsonObjectProperty property, out Menes.OpenApiSchema.V31.Document.Components.SchemasResponsesParametersExamplesRequestBodiesHeadersSecuritySchemesLinksCallbacksPathItemsEntity result)
        {
            if (PatternPropertySchemasResponsesParametersExamplesRequestBodiesHeadersSecuritySchemesLinksCallbacksPathItemsEntity.IsMatch(property.Name))
            {
                result = property.ValueAs<Menes.OpenApiSchema.V31.Document.Components.SchemasResponsesParametersExamplesRequestBodiesHeadersSecuritySchemesLinksCallbacksPathItemsEntity>();
                return true;
            }
            else
            {
                result = Menes.OpenApiSchema.V31.Document.Components.SchemasResponsesParametersExamplesRequestBodiesHeadersSecuritySchemesLinksCallbacksPathItemsEntity.Undefined;
                return false;
            }
        }

        /// <summary>
        /// Try to get a property value as the type matching the given pattern property ^(schemas|responses|parameters|examples|requestBodies|headers|securitySchemes|links|callbacks|pathItems)$ as a <see cref = "Menes.OpenApiSchema.V31.Document.Components.SchemasResponsesParametersExamplesRequestBodiesHeadersSecuritySchemesLinksCallbacksPathItemsEntity"/>.
        /// </summary>
        public Menes.OpenApiSchema.V31.Document.Components.SchemasResponsesParametersExamplesRequestBodiesHeadersSecuritySchemesLinksCallbacksPathItemsEntity AsPatternSchemasResponsesParametersExamplesRequestBodiesHeadersSecuritySchemesLinksCallbacksPathItemsEntity(in JsonObjectProperty property)
        {
            return property.ValueAs<Menes.OpenApiSchema.V31.Document.Components.SchemasResponsesParametersExamplesRequestBodiesHeadersSecuritySchemesLinksCallbacksPathItemsEntity>();
        }

        private static ImmutableDictionary<Regex, PatternPropertyValidator> CreatePatternPropertiesValidators()
        {
            ImmutableDictionary<Regex, PatternPropertyValidator>.Builder builder = ImmutableDictionary.CreateBuilder<Regex, PatternPropertyValidator>();
            builder.Add(PatternPropertySchemasResponsesParametersExamplesRequestBodiesHeadersSecuritySchemesLinksCallbacksPathItemsEntity, __CorvusValidatePatternPropertySchemasResponsesParametersExamplesRequestBodiesHeadersSecuritySchemesLinksCallbacksPathItemsEntity);
            return builder.ToImmutable();
        }

        private static ValidationContext __CorvusValidatePatternPropertySchemasResponsesParametersExamplesRequestBodiesHeadersSecuritySchemesLinksCallbacksPathItemsEntity(in JsonObjectProperty that, in ValidationContext validationContext, ValidationLevel level)
        {
            return that.ValueAs<Menes.OpenApiSchema.V31.Document.Components.SchemasResponsesParametersExamplesRequestBodiesHeadersSecuritySchemesLinksCallbacksPathItemsEntity>().Validate(validationContext, level);
        }
    }
}