//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace Menes.OpenApiSchema.V31;
public readonly partial struct Document
{
    /// <summary>
    /// A type generated from a JsonSchema specification.
    /// </summary>
    public readonly partial struct AnyOf2Entity
    {
        /// <summary>
        /// JSON property name for <see cref = "Webhooks"/>.
        /// </summary>
        public static readonly ReadOnlyMemory<byte> WebhooksUtf8JsonPropertyName = new byte[]{119, 101, 98, 104, 111, 111, 107, 115};
        /// <summary>
        /// JSON property name for <see cref = "Webhooks"/>.
        /// </summary>
        public const string WebhooksJsonPropertyName = "webhooks";
        /// <summary>
        /// Gets Webhooks.
        /// </summary>
        public Corvus.Json.JsonAny Webhooks
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(WebhooksUtf8JsonPropertyName.Span, out JsonElement result))
                    {
                        return new Corvus.Json.JsonAny(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(WebhooksJsonPropertyName, out JsonAny result))
                    {
                        return result.As<Corvus.Json.JsonAny>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Creates an instance of a <see cref = "AnyOf2Entity"/>.
        /// </summary>
        public static AnyOf2Entity Create(Corvus.Json.JsonAny webhooks)
        {
            var builder = ImmutableDictionary.CreateBuilder<JsonPropertyName, JsonAny>();
            builder.Add(WebhooksJsonPropertyName, webhooks.AsAny);
            return builder.ToImmutable();
        }

        /// <summary>
        /// Sets webhooks.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public AnyOf2Entity WithWebhooks(in Corvus.Json.JsonAny value)
        {
            return this.SetProperty(WebhooksJsonPropertyName, value);
        }

        private static ValidationContext __CorvusValidateWebhooks(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Corvus.Json.JsonAny>().Validate(validationContext, level);
        }

        /// <summary>
        /// Tries to get the validator for the given property.
        /// </summary>
        /// <param name = "property">The property for which to get the validator.</param>
        /// <param name = "hasJsonElementBacking"><c>True</c> if the object containing the property has a JsonElement backing.</param>
        /// <param name = "propertyValidator">The validator for the property, if provided by this schema.</param>
        /// <returns><c>True</c> if the validator was found.</returns>
        private bool __TryGetCorvusLocalPropertiesValidator(in JsonObjectProperty property, bool hasJsonElementBacking, [NotNullWhen(true)] out ObjectPropertyValidator? propertyValidator)
        {
            if (hasJsonElementBacking)
            {
                if (property.NameEquals(WebhooksUtf8JsonPropertyName.Span))
                {
                    propertyValidator = __CorvusValidateWebhooks;
                    return true;
                }
            }
            else
            {
                if (property.NameEquals(WebhooksJsonPropertyName))
                {
                    propertyValidator = __CorvusValidateWebhooks;
                    return true;
                }
            }

            propertyValidator = null;
            return false;
        }
    }
}