//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace Menes.OpenApiSchema.V31;
public readonly partial struct Document
{
    public readonly partial struct SecurityScheme
    {
        public readonly partial struct TypeApikeyEntity
        {
            /// <summary>
            /// A type generated from a JsonSchema specification.
            /// </summary>
            public readonly partial struct IfEntity
            {
                /// <summary>
                /// JSON property name for <see cref = "Type"/>.
                /// </summary>
                public static readonly ReadOnlyMemory<byte> TypeUtf8JsonPropertyName = new byte[]{116, 121, 112, 101};
                /// <summary>
                /// JSON property name for <see cref = "Type"/>.
                /// </summary>
                public const string TypeJsonPropertyName = "type";
                /// <summary>
                /// Gets Type.
                /// </summary>
                public Menes.OpenApiSchema.V31.Document.SecurityScheme.TypeApikeyEntity.IfEntity.TypeEntity Type
                {
                    get
                    {
                        if ((this.backing & Backing.JsonElement) != 0)
                        {
                            if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                            {
                                return default;
                            }

                            if (this.jsonElementBacking.TryGetProperty(TypeUtf8JsonPropertyName.Span, out JsonElement result))
                            {
                                return new Menes.OpenApiSchema.V31.Document.SecurityScheme.TypeApikeyEntity.IfEntity.TypeEntity(result);
                            }
                        }

                        if ((this.backing & Backing.Object) != 0)
                        {
                            if (this.objectBacking.TryGetValue(TypeJsonPropertyName, out JsonAny result))
                            {
                                return result.As<Menes.OpenApiSchema.V31.Document.SecurityScheme.TypeApikeyEntity.IfEntity.TypeEntity>();
                            }
                        }

                        return default;
                    }
                }

                /// <summary>
                /// Creates an instance of a <see cref = "IfEntity"/>.
                /// </summary>
                public static IfEntity Create()
                {
                    var builder = ImmutableDictionary.CreateBuilder<JsonPropertyName, JsonAny>();
                    builder.Add(TypeJsonPropertyName, new Menes.OpenApiSchema.V31.Document.SecurityScheme.TypeApikeyEntity.IfEntity.TypeEntity().AsAny);
                    return builder.ToImmutable();
                }

                private static ValidationContext __CorvusValidateType(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
                {
                    return property.ValueAs<Menes.OpenApiSchema.V31.Document.SecurityScheme.TypeApikeyEntity.IfEntity.TypeEntity>().Validate(validationContext, level);
                }

                /// <summary>
                /// Tries to get the validator for the given property.
                /// </summary>
                /// <param name = "property">The property for which to get the validator.</param>
                /// <param name = "hasJsonElementBacking"><c>True</c> if the object containing the property has a JsonElement backing.</param>
                /// <param name = "propertyValidator">The validator for the property, if provided by this schema.</param>
                /// <returns><c>True</c> if the validator was found.</returns>
                private bool __TryGetCorvusLocalPropertiesValidator(in JsonObjectProperty property, bool hasJsonElementBacking, [NotNullWhen(true)] out ObjectPropertyValidator? propertyValidator)
                {
                    if (hasJsonElementBacking)
                    {
                        if (property.NameEquals(TypeUtf8JsonPropertyName.Span))
                        {
                            propertyValidator = __CorvusValidateType;
                            return true;
                        }
                    }
                    else
                    {
                        if (property.NameEquals(TypeJsonPropertyName))
                        {
                            propertyValidator = __CorvusValidateType;
                            return true;
                        }
                    }

                    propertyValidator = null;
                    return false;
                }
            }
        }
    }
}