//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.CompilerServices;
using System.Text.Json;
using Corvus.Json;
using Corvus.Json.Internal;

namespace Menes.OpenApiSchema.V31;
public readonly partial struct Document
{
    /// <summary>
    /// A type generated from a JsonSchema specification.
    /// </summary>
    public readonly partial struct Components
    {
        /// <summary>
        /// JSON property name for <see cref = "Schemas"/>.
        /// </summary>
        public static readonly ReadOnlyMemory<byte> SchemasUtf8JsonPropertyName = new byte[]{115, 99, 104, 101, 109, 97, 115};
        /// <summary>
        /// JSON property name for <see cref = "Schemas"/>.
        /// </summary>
        public const string SchemasJsonPropertyName = "schemas";
        /// <summary>
        /// JSON property name for <see cref = "Responses"/>.
        /// </summary>
        public static readonly ReadOnlyMemory<byte> ResponsesUtf8JsonPropertyName = new byte[]{114, 101, 115, 112, 111, 110, 115, 101, 115};
        /// <summary>
        /// JSON property name for <see cref = "Responses"/>.
        /// </summary>
        public const string ResponsesJsonPropertyName = "responses";
        /// <summary>
        /// JSON property name for <see cref = "Parameters"/>.
        /// </summary>
        public static readonly ReadOnlyMemory<byte> ParametersUtf8JsonPropertyName = new byte[]{112, 97, 114, 97, 109, 101, 116, 101, 114, 115};
        /// <summary>
        /// JSON property name for <see cref = "Parameters"/>.
        /// </summary>
        public const string ParametersJsonPropertyName = "parameters";
        /// <summary>
        /// JSON property name for <see cref = "Examples"/>.
        /// </summary>
        public static readonly ReadOnlyMemory<byte> ExamplesUtf8JsonPropertyName = new byte[]{101, 120, 97, 109, 112, 108, 101, 115};
        /// <summary>
        /// JSON property name for <see cref = "Examples"/>.
        /// </summary>
        public const string ExamplesJsonPropertyName = "examples";
        /// <summary>
        /// JSON property name for <see cref = "RequestBodies"/>.
        /// </summary>
        public static readonly ReadOnlyMemory<byte> RequestBodiesUtf8JsonPropertyName = new byte[]{114, 101, 113, 117, 101, 115, 116, 66, 111, 100, 105, 101, 115};
        /// <summary>
        /// JSON property name for <see cref = "RequestBodies"/>.
        /// </summary>
        public const string RequestBodiesJsonPropertyName = "requestBodies";
        /// <summary>
        /// JSON property name for <see cref = "Headers"/>.
        /// </summary>
        public static readonly ReadOnlyMemory<byte> HeadersUtf8JsonPropertyName = new byte[]{104, 101, 97, 100, 101, 114, 115};
        /// <summary>
        /// JSON property name for <see cref = "Headers"/>.
        /// </summary>
        public const string HeadersJsonPropertyName = "headers";
        /// <summary>
        /// JSON property name for <see cref = "SecuritySchemes"/>.
        /// </summary>
        public static readonly ReadOnlyMemory<byte> SecuritySchemesUtf8JsonPropertyName = new byte[]{115, 101, 99, 117, 114, 105, 116, 121, 83, 99, 104, 101, 109, 101, 115};
        /// <summary>
        /// JSON property name for <see cref = "SecuritySchemes"/>.
        /// </summary>
        public const string SecuritySchemesJsonPropertyName = "securitySchemes";
        /// <summary>
        /// JSON property name for <see cref = "Links"/>.
        /// </summary>
        public static readonly ReadOnlyMemory<byte> LinksUtf8JsonPropertyName = new byte[]{108, 105, 110, 107, 115};
        /// <summary>
        /// JSON property name for <see cref = "Links"/>.
        /// </summary>
        public const string LinksJsonPropertyName = "links";
        /// <summary>
        /// JSON property name for <see cref = "Callbacks"/>.
        /// </summary>
        public static readonly ReadOnlyMemory<byte> CallbacksUtf8JsonPropertyName = new byte[]{99, 97, 108, 108, 98, 97, 99, 107, 115};
        /// <summary>
        /// JSON property name for <see cref = "Callbacks"/>.
        /// </summary>
        public const string CallbacksJsonPropertyName = "callbacks";
        /// <summary>
        /// JSON property name for <see cref = "PathItems"/>.
        /// </summary>
        public static readonly ReadOnlyMemory<byte> PathItemsUtf8JsonPropertyName = new byte[]{112, 97, 116, 104, 73, 116, 101, 109, 115};
        /// <summary>
        /// JSON property name for <see cref = "PathItems"/>.
        /// </summary>
        public const string PathItemsJsonPropertyName = "pathItems";
        /// <summary>
        /// Gets Schemas.
        /// </summary>
        public Menes.OpenApiSchema.V31.Document.Components.SchemasEntity Schemas
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(SchemasUtf8JsonPropertyName.Span, out JsonElement result))
                    {
                        return new Menes.OpenApiSchema.V31.Document.Components.SchemasEntity(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(SchemasJsonPropertyName, out JsonAny result))
                    {
                        return result.As<Menes.OpenApiSchema.V31.Document.Components.SchemasEntity>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets Responses.
        /// </summary>
        public Menes.OpenApiSchema.V31.Document.Components.ResponsesEntity Responses
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(ResponsesUtf8JsonPropertyName.Span, out JsonElement result))
                    {
                        return new Menes.OpenApiSchema.V31.Document.Components.ResponsesEntity(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(ResponsesJsonPropertyName, out JsonAny result))
                    {
                        return result.As<Menes.OpenApiSchema.V31.Document.Components.ResponsesEntity>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets Parameters.
        /// </summary>
        public Menes.OpenApiSchema.V31.Document.Components.ParametersEntity Parameters
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(ParametersUtf8JsonPropertyName.Span, out JsonElement result))
                    {
                        return new Menes.OpenApiSchema.V31.Document.Components.ParametersEntity(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(ParametersJsonPropertyName, out JsonAny result))
                    {
                        return result.As<Menes.OpenApiSchema.V31.Document.Components.ParametersEntity>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets Examples.
        /// </summary>
        public Menes.OpenApiSchema.V31.Document.Components.ExamplesEntity Examples
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(ExamplesUtf8JsonPropertyName.Span, out JsonElement result))
                    {
                        return new Menes.OpenApiSchema.V31.Document.Components.ExamplesEntity(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(ExamplesJsonPropertyName, out JsonAny result))
                    {
                        return result.As<Menes.OpenApiSchema.V31.Document.Components.ExamplesEntity>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets RequestBodies.
        /// </summary>
        public Menes.OpenApiSchema.V31.Document.Components.RequestBodiesEntity RequestBodies
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(RequestBodiesUtf8JsonPropertyName.Span, out JsonElement result))
                    {
                        return new Menes.OpenApiSchema.V31.Document.Components.RequestBodiesEntity(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(RequestBodiesJsonPropertyName, out JsonAny result))
                    {
                        return result.As<Menes.OpenApiSchema.V31.Document.Components.RequestBodiesEntity>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets Headers.
        /// </summary>
        public Menes.OpenApiSchema.V31.Document.Components.HeadersEntity Headers
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(HeadersUtf8JsonPropertyName.Span, out JsonElement result))
                    {
                        return new Menes.OpenApiSchema.V31.Document.Components.HeadersEntity(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(HeadersJsonPropertyName, out JsonAny result))
                    {
                        return result.As<Menes.OpenApiSchema.V31.Document.Components.HeadersEntity>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets SecuritySchemes.
        /// </summary>
        public Menes.OpenApiSchema.V31.Document.Components.SecuritySchemesEntity SecuritySchemes
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(SecuritySchemesUtf8JsonPropertyName.Span, out JsonElement result))
                    {
                        return new Menes.OpenApiSchema.V31.Document.Components.SecuritySchemesEntity(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(SecuritySchemesJsonPropertyName, out JsonAny result))
                    {
                        return result.As<Menes.OpenApiSchema.V31.Document.Components.SecuritySchemesEntity>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets Links.
        /// </summary>
        public Menes.OpenApiSchema.V31.Document.Components.LinksEntity Links
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(LinksUtf8JsonPropertyName.Span, out JsonElement result))
                    {
                        return new Menes.OpenApiSchema.V31.Document.Components.LinksEntity(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(LinksJsonPropertyName, out JsonAny result))
                    {
                        return result.As<Menes.OpenApiSchema.V31.Document.Components.LinksEntity>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets Callbacks.
        /// </summary>
        public Menes.OpenApiSchema.V31.Document.Components.CallbacksEntity Callbacks
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(CallbacksUtf8JsonPropertyName.Span, out JsonElement result))
                    {
                        return new Menes.OpenApiSchema.V31.Document.Components.CallbacksEntity(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(CallbacksJsonPropertyName, out JsonAny result))
                    {
                        return result.As<Menes.OpenApiSchema.V31.Document.Components.CallbacksEntity>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Gets PathItems.
        /// </summary>
        public Menes.OpenApiSchema.V31.Document.Components.PathItemsEntity PathItems
        {
            get
            {
                if ((this.backing & Backing.JsonElement) != 0)
                {
                    if (this.jsonElementBacking.ValueKind != JsonValueKind.Object)
                    {
                        return default;
                    }

                    if (this.jsonElementBacking.TryGetProperty(PathItemsUtf8JsonPropertyName.Span, out JsonElement result))
                    {
                        return new Menes.OpenApiSchema.V31.Document.Components.PathItemsEntity(result);
                    }
                }

                if ((this.backing & Backing.Object) != 0)
                {
                    if (this.objectBacking.TryGetValue(PathItemsJsonPropertyName, out JsonAny result))
                    {
                        return result.As<Menes.OpenApiSchema.V31.Document.Components.PathItemsEntity>();
                    }
                }

                return default;
            }
        }

        /// <summary>
        /// Creates an instance of a <see cref = "Components"/>.
        /// </summary>
        public static Components Create(Menes.OpenApiSchema.V31.Document.Components.SchemasEntity? schemas = null, Menes.OpenApiSchema.V31.Document.Components.ResponsesEntity? responses = null, Menes.OpenApiSchema.V31.Document.Components.ParametersEntity? parameters = null, Menes.OpenApiSchema.V31.Document.Components.ExamplesEntity? examples = null, Menes.OpenApiSchema.V31.Document.Components.RequestBodiesEntity? requestBodies = null, Menes.OpenApiSchema.V31.Document.Components.HeadersEntity? headers = null, Menes.OpenApiSchema.V31.Document.Components.SecuritySchemesEntity? securitySchemes = null, Menes.OpenApiSchema.V31.Document.Components.LinksEntity? links = null, Menes.OpenApiSchema.V31.Document.Components.CallbacksEntity? callbacks = null, Menes.OpenApiSchema.V31.Document.Components.PathItemsEntity? pathItems = null)
        {
            var builder = ImmutableDictionary.CreateBuilder<JsonPropertyName, JsonAny>();
            if (schemas is Menes.OpenApiSchema.V31.Document.Components.SchemasEntity schemas__)
            {
                builder.Add(SchemasJsonPropertyName, schemas__.AsAny);
            }

            if (responses is Menes.OpenApiSchema.V31.Document.Components.ResponsesEntity responses__)
            {
                builder.Add(ResponsesJsonPropertyName, responses__.AsAny);
            }

            if (parameters is Menes.OpenApiSchema.V31.Document.Components.ParametersEntity parameters__)
            {
                builder.Add(ParametersJsonPropertyName, parameters__.AsAny);
            }

            if (examples is Menes.OpenApiSchema.V31.Document.Components.ExamplesEntity examples__)
            {
                builder.Add(ExamplesJsonPropertyName, examples__.AsAny);
            }

            if (requestBodies is Menes.OpenApiSchema.V31.Document.Components.RequestBodiesEntity requestBodies__)
            {
                builder.Add(RequestBodiesJsonPropertyName, requestBodies__.AsAny);
            }

            if (headers is Menes.OpenApiSchema.V31.Document.Components.HeadersEntity headers__)
            {
                builder.Add(HeadersJsonPropertyName, headers__.AsAny);
            }

            if (securitySchemes is Menes.OpenApiSchema.V31.Document.Components.SecuritySchemesEntity securitySchemes__)
            {
                builder.Add(SecuritySchemesJsonPropertyName, securitySchemes__.AsAny);
            }

            if (links is Menes.OpenApiSchema.V31.Document.Components.LinksEntity links__)
            {
                builder.Add(LinksJsonPropertyName, links__.AsAny);
            }

            if (callbacks is Menes.OpenApiSchema.V31.Document.Components.CallbacksEntity callbacks__)
            {
                builder.Add(CallbacksJsonPropertyName, callbacks__.AsAny);
            }

            if (pathItems is Menes.OpenApiSchema.V31.Document.Components.PathItemsEntity pathItems__)
            {
                builder.Add(PathItemsJsonPropertyName, pathItems__.AsAny);
            }

            return builder.ToImmutable();
        }

        /// <summary>
        /// Sets schemas.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public Components WithSchemas(in Menes.OpenApiSchema.V31.Document.Components.SchemasEntity value)
        {
            return this.SetProperty(SchemasJsonPropertyName, value);
        }

        /// <summary>
        /// Sets responses.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public Components WithResponses(in Menes.OpenApiSchema.V31.Document.Components.ResponsesEntity value)
        {
            return this.SetProperty(ResponsesJsonPropertyName, value);
        }

        /// <summary>
        /// Sets parameters.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public Components WithParameters(in Menes.OpenApiSchema.V31.Document.Components.ParametersEntity value)
        {
            return this.SetProperty(ParametersJsonPropertyName, value);
        }

        /// <summary>
        /// Sets examples.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public Components WithExamples(in Menes.OpenApiSchema.V31.Document.Components.ExamplesEntity value)
        {
            return this.SetProperty(ExamplesJsonPropertyName, value);
        }

        /// <summary>
        /// Sets requestBodies.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public Components WithRequestBodies(in Menes.OpenApiSchema.V31.Document.Components.RequestBodiesEntity value)
        {
            return this.SetProperty(RequestBodiesJsonPropertyName, value);
        }

        /// <summary>
        /// Sets headers.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public Components WithHeaders(in Menes.OpenApiSchema.V31.Document.Components.HeadersEntity value)
        {
            return this.SetProperty(HeadersJsonPropertyName, value);
        }

        /// <summary>
        /// Sets securitySchemes.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public Components WithSecuritySchemes(in Menes.OpenApiSchema.V31.Document.Components.SecuritySchemesEntity value)
        {
            return this.SetProperty(SecuritySchemesJsonPropertyName, value);
        }

        /// <summary>
        /// Sets links.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public Components WithLinks(in Menes.OpenApiSchema.V31.Document.Components.LinksEntity value)
        {
            return this.SetProperty(LinksJsonPropertyName, value);
        }

        /// <summary>
        /// Sets callbacks.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public Components WithCallbacks(in Menes.OpenApiSchema.V31.Document.Components.CallbacksEntity value)
        {
            return this.SetProperty(CallbacksJsonPropertyName, value);
        }

        /// <summary>
        /// Sets pathItems.
        /// </summary>
        /// <param name = "value">The value to set.</param>
        /// <returns>The entity with the updated property.</returns>
        public Components WithPathItems(in Menes.OpenApiSchema.V31.Document.Components.PathItemsEntity value)
        {
            return this.SetProperty(PathItemsJsonPropertyName, value);
        }

        private static ValidationContext __CorvusValidateSchemas(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Menes.OpenApiSchema.V31.Document.Components.SchemasEntity>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateResponses(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Menes.OpenApiSchema.V31.Document.Components.ResponsesEntity>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateParameters(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Menes.OpenApiSchema.V31.Document.Components.ParametersEntity>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateExamples(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Menes.OpenApiSchema.V31.Document.Components.ExamplesEntity>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateRequestBodies(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Menes.OpenApiSchema.V31.Document.Components.RequestBodiesEntity>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateHeaders(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Menes.OpenApiSchema.V31.Document.Components.HeadersEntity>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateSecuritySchemes(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Menes.OpenApiSchema.V31.Document.Components.SecuritySchemesEntity>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateLinks(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Menes.OpenApiSchema.V31.Document.Components.LinksEntity>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidateCallbacks(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Menes.OpenApiSchema.V31.Document.Components.CallbacksEntity>().Validate(validationContext, level);
        }

        private static ValidationContext __CorvusValidatePathItems(in JsonObjectProperty property, in ValidationContext validationContext, ValidationLevel level)
        {
            return property.ValueAs<Menes.OpenApiSchema.V31.Document.Components.PathItemsEntity>().Validate(validationContext, level);
        }

        /// <summary>
        /// Tries to get the validator for the given property.
        /// </summary>
        /// <param name = "property">The property for which to get the validator.</param>
        /// <param name = "hasJsonElementBacking"><c>True</c> if the object containing the property has a JsonElement backing.</param>
        /// <param name = "propertyValidator">The validator for the property, if provided by this schema.</param>
        /// <returns><c>True</c> if the validator was found.</returns>
        private bool __TryGetCorvusLocalPropertiesValidator(in JsonObjectProperty property, bool hasJsonElementBacking, [NotNullWhen(true)] out ObjectPropertyValidator? propertyValidator)
        {
            if (hasJsonElementBacking)
            {
                if (property.NameEquals(SchemasUtf8JsonPropertyName.Span))
                {
                    propertyValidator = __CorvusValidateSchemas;
                    return true;
                }
                else if (property.NameEquals(ResponsesUtf8JsonPropertyName.Span))
                {
                    propertyValidator = __CorvusValidateResponses;
                    return true;
                }
                else if (property.NameEquals(ParametersUtf8JsonPropertyName.Span))
                {
                    propertyValidator = __CorvusValidateParameters;
                    return true;
                }
                else if (property.NameEquals(ExamplesUtf8JsonPropertyName.Span))
                {
                    propertyValidator = __CorvusValidateExamples;
                    return true;
                }
                else if (property.NameEquals(RequestBodiesUtf8JsonPropertyName.Span))
                {
                    propertyValidator = __CorvusValidateRequestBodies;
                    return true;
                }
                else if (property.NameEquals(HeadersUtf8JsonPropertyName.Span))
                {
                    propertyValidator = __CorvusValidateHeaders;
                    return true;
                }
                else if (property.NameEquals(SecuritySchemesUtf8JsonPropertyName.Span))
                {
                    propertyValidator = __CorvusValidateSecuritySchemes;
                    return true;
                }
                else if (property.NameEquals(LinksUtf8JsonPropertyName.Span))
                {
                    propertyValidator = __CorvusValidateLinks;
                    return true;
                }
                else if (property.NameEquals(CallbacksUtf8JsonPropertyName.Span))
                {
                    propertyValidator = __CorvusValidateCallbacks;
                    return true;
                }
                else if (property.NameEquals(PathItemsUtf8JsonPropertyName.Span))
                {
                    propertyValidator = __CorvusValidatePathItems;
                    return true;
                }
            }
            else
            {
                if (property.NameEquals(SchemasJsonPropertyName))
                {
                    propertyValidator = __CorvusValidateSchemas;
                    return true;
                }
                else if (property.NameEquals(ResponsesJsonPropertyName))
                {
                    propertyValidator = __CorvusValidateResponses;
                    return true;
                }
                else if (property.NameEquals(ParametersJsonPropertyName))
                {
                    propertyValidator = __CorvusValidateParameters;
                    return true;
                }
                else if (property.NameEquals(ExamplesJsonPropertyName))
                {
                    propertyValidator = __CorvusValidateExamples;
                    return true;
                }
                else if (property.NameEquals(RequestBodiesJsonPropertyName))
                {
                    propertyValidator = __CorvusValidateRequestBodies;
                    return true;
                }
                else if (property.NameEquals(HeadersJsonPropertyName))
                {
                    propertyValidator = __CorvusValidateHeaders;
                    return true;
                }
                else if (property.NameEquals(SecuritySchemesJsonPropertyName))
                {
                    propertyValidator = __CorvusValidateSecuritySchemes;
                    return true;
                }
                else if (property.NameEquals(LinksJsonPropertyName))
                {
                    propertyValidator = __CorvusValidateLinks;
                    return true;
                }
                else if (property.NameEquals(CallbacksJsonPropertyName))
                {
                    propertyValidator = __CorvusValidateCallbacks;
                    return true;
                }
                else if (property.NameEquals(PathItemsJsonPropertyName))
                {
                    propertyValidator = __CorvusValidatePathItems;
                    return true;
                }
            }

            propertyValidator = null;
            return false;
        }
    }
}