// <copyright file="GlobalSuppressions.cs" company="Endjin">
// Copyright (c) Endjin. All rights reserved.
// </copyright>

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("General", "RCS1079:Throwing of new NotImplementedException.", Justification = "Approved means of implementing unsupported read/write methods", Scope = "member", Target = "~M:Endjin.OpenApi.Internal.HttpRequestParameterBuilder.ConvertValue(Microsoft.OpenApi.Models.OpenApiSchema,System.String)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("General", "RCS1079:Throwing of new NotImplementedException.", Justification = "Approved means of implementing unsupported read/write methods", Scope = "member", Target = "~M:Endjin.OpenApi.Internal.OpenApiActionResult.ConvertValue(Microsoft.OpenApi.Models.OpenApiSchema,System.Object)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("General", "RCS1079:Throwing of new NotImplementedException.", Justification = "Approved means of implementing unsupported read/write methods", Scope = "member", Target = "~M:Endjin.OpenApi.Internal.OpenApiLinkCollectionJsonConverter.ReadJson(Newtonsoft.Json.JsonReader,System.Type,System.Object,Newtonsoft.Json.JsonSerializer)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("General", "RCS1079:Throwing of new NotImplementedException.", Justification = "Approved means of implementing unsupported read/write methods", Scope = "member", Target = "~M:Endjin.OpenApi.OpenApiHttpRequestHost.ExecuteOperation(Microsoft.AspNetCore.Http.HttpRequest,Endjin.OpenApi.Internal.MatchResult)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("General", "RCS1079:Throwing of new NotImplementedException.", Justification = "Approved means of implementing unsupported read/write methods", Scope = "member", Target = "~M:Endjin.OpenApi.Internal.HalWebLinkCollectionJsonConverter.ReadJson(Newtonsoft.Json.JsonReader,System.Type,System.Object,Newtonsoft.Json.JsonSerializer)~System.Object")]
