name: auto_release
on: 
  pull_request:
    types: [closed]

env:
  # Customise this variable to choose which dependencies can be auto-merged
  AUTO_MERGE_PACKAGE_WILDCARD_EXPRESSIONS: |
    ["Endjin.*","Corvus.*"]

jobs:
  check_for_open_prs:
    runs-on: ubuntu-latest
    if: |
      (github.actor == 'endjin-bot[bot]' || github.actor == 'nektos/act')
    outputs:
      no_open_prs: ${{ steps.watch_dependabot_prs.outputs.is_complete }}
    steps:
    - id: get_pr_list
      name: Get PRs
      uses: actions/github-script@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const pulls = await github.pulls.list({
            owner: context.payload.repository.owner.login,
            repo: context.payload.repository.name,
            state: 'open',
            base: 'master'
          });
          return JSON.stringify(pulls.data.map(p=>p.title))
        result-encoding: string

    - name: Display pr_list
      run: |
        echo "pr_list : ${{ steps.get_pr_list.outputs.result }}"

    - id: watch_dependabot_prs
      name: Watch Dependabot PRs
      uses: endjin/pr-autoflow/actions/dependabot-pr-watcher@v3
      with:
        pr_titles: ${{ steps.get_pr_list.outputs.result }}
        package_wildcard_expressions: ${{ env.AUTO_MERGE_PACKAGE_WILDCARD_EXPRESSIONS }}
        max_semver_increment: minor
        verbose_mode: 'False'

  tag_for_release:
    runs-on: ubuntu-latest
    needs: check_for_open_prs
    if: |
      (needs.check_for_open_prs.outputs.no_open_prs == 'True')
    steps:
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.2
      with:
        versionSpec: '5.2.x'
    
    - uses: actions/checkout@v2

    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow

    - name: Use GitVersion
      id: gitversion 
      uses: gittools/actions/gitversion/execute@v0.9.2
      with:
        additionalArguments: |
          /overrideconfig increment=patch

    - uses: hole19/git-tag-action@master
      env:
        TAG: ${{ steps.gitversion.outputs.semver }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
